### ISSUE TITLE
lua.exe: error loading module 'lfs' from file 'luaclib/lfs.dll'

### ISSUE THREAD

**Issue by huahuacn** [zhangshiqian1214/sprototool#1]
如题，我自己手动编译了一个lua5.3.2，然后调用test_dumpsproto.lua，在生成spb文件时提示：
lua.exe: error loading module 'lfs' from file 'luaclib/lfs.dll'
%1 不是有效的win32应用程序。

请问此问题如何解决呀。操作系统是windows 10。

**Comment by zhangshiqian1214** [comment]
没有生成lfs.dll, 所以没有加载到
