### ISSUE TITLE
How to serialize this proto files to sproto?

### ISSUE THREAD

**Issue by murat8505** [zhangshiqian1214/sprototool#3]
How to serialize this proto files to sproto:

package com.tutorial;

option java_package = "com.example.tutorial";
option java_outer_classname = "AddressBookProtos";

message Profile {
  optional string nick_name = 1;
  optional string icon = 2;
}

message Person {
  required string name = 1;
  required int32 id = 2;        // Unique ID number for this person.
  optional string email = 3;

  enum PhoneType {
    MOBILE = 0;
    HOME = 1;
    WORK = 2;
  }

  message PhoneNumber {
    required string number = 1;
    optional PhoneType type = 2 [default = HOME];
  }

  repeated PhoneNumber phone = 4;
  repeated int32 test = 5 [packed=true];

  optional Profile profile = 6;

  extensions 10 to max; 
}

message Ext {
  extend Person {
    optional int32 test = 10;
  }
}

// Our address book file is just one of these.
message AddressBook {
  repeated Person person = 1;
}

**Comment by zhangshiqian1214** [comment]
maybe https://github.com/cloudwu/sproto can help you
